### ISSUE TITLE
Print all at once when all cached

### ISSUE THREAD

**Issue by superna9999** [montjoie/lavatop#3]
On launch, I see only workers printed for a few seconds before showing all infos :
![Screenshot from 2020-05-13 11-40-23](https://user-images.githubusercontent.com/492099/81797159-b4958500-950e-11ea-910d-a5e0ce297357.png)

Would be nice to have a "Loading..." status then showing everything at once

**Comment by montjoie** [comment]
this will be fixed with the "update threading"
